Explain parameter promotion in ClassesVsCaseClasses
Replaces usage of the phrase "not the case" w/ "not true" since the word "case" is heavily used.  Also expands on what does happen to class parameters and adds a code snippet to demonstrate (hope I conformed here stylistically? 

Raw REPL output ala

```
scala> class MyClass(x: Int) { def doubledX = x * 2}
defined class MyClass

scala> val myInstance = new MyClass(5)
myInstance: MyClass = MyClass@129b4fe2

scala> myInstance.doubledX
res0: Int = 10

scala> myInstance.x
<console>:14: error: value x is not a member of MyClass
       myInstance.x
```

does not appear to be used anywhere