Rectified `to is not a member of Boolean` error
Due to the order of evaluation, 
1.to(10) == 1 gets evaluated to False
and the expression becomes
False to 10